# Generated by Django 3.1.5 on 2021-03-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20210312_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
